name: autodeploy

on:
  push:
    branches:
      - autodeploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      # - name: Run a docker-compose script
      #   run: |
      #     cd labs/K33401/Baltsat_Konstantin/lab3_4
      #     docker-compose up

      - name: Docker compose
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./labs/K33401/Baltsat_Konstantin/lab3_4/docker-compose.yml"
        env:
          DB_USERNAME: postgres
          DB_COINS: cryptocoin_ms
          DB_AUTH: cryptocoin_auth_ms


    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Set up SSH
    #     uses: webfactory/ssh-agent@v0.5.0
    #     with:
    #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    #   - name: Install dependencies and build
    #     run: |
    #       cd auth-service
    #       npm install
    #       npm run build

    #   - name: Deploy to remote server
    #     run: |
    #       ssh user@your-server-ip "cd /path/to/your/app && git pull origin autodeploy && docker-compose up -d"
