name: autodeploy

on:
  push:
    branches:
      - autodeploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Set up SSH
    #     uses: webfactory/ssh-agent@v0.5.0
    #     with:
    #       ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    #   - name: Install dependencies and build
    #     run: |
    #       cd auth-service
    #       npm install
    #       npm run build

    #   - name: Deploy to remote server
    #     run: |
    #       ssh user@your-server-ip "cd /path/to/your/app && git pull origin autodeploy && docker-compose up -d"
