name: autodeploy

on:
  push:
    branches:
      - autodeploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Docker compose
      #   uses: isbang/compose-action@v1.4.1
      #   with:
      #     compose-file: "./labs/K33401/Baltsat_Konstantin/lab3_4/docker-compose.yml"
      #   env:
      #     DB_USERNAME: postgres
      #     DB_COINS: cryptocoin_ms
      #     DB_AUTH: cryptocoin_auth_ms


      - name: SSH into remote server and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PRIVATE_KEY }}
          script: |
            git pull origin autodeploy
            cd ITMO-ICT-Backend-2023/labs/K33401/Baltsat_Konstantin/lab3_4
            docker-compose down
            docker-compose up -d

    #   - name: Set up SSH
    #     uses: webfactory/ssh-agent@v0.5.0
    #     with:
    #       ssh-private-key: ${{ secrets.REMOTE_PRIVATE_KEY }}

    #   - name: Install dependencies and build
    #     run: |
    #       cd auth-service
    #       npm install
    #       npm run build

    #   - name: Deploy to remote server
    #     run: |
    #       ssh admin@${{ secrets.REMOTE_HOST }} "cd /deploy && git pull origin autodeploy && docker-compose up -d"
